version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: deep-learning-from-scratch
    ports:
      - "8888:8888"
    tty: true
    volumes:
      - .:/deep-learning-from-scratch-1st